version: "3.1"

services:
  php:
    build: ./configuration/php
    working_dir: /app
    volumes:
      - ./app:/app
      - ./configuration/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
  nginx:
    image: nginx:stable
    working_dir: /app
    volumes:
      - ./app:/app
      - ./configuration/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  mysql:
    image: mysql:8
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    ports:
      - "5672:5672"
    
